### ISSUE TITLE
Can't spawn any mob and don't see icons.

### ISSUE THREAD

**Issue by 4ertos** [RileSamurott/Providirector#10]
I have a problem while running providirector, I don't see any Icons of mobs and can't spawn them aswell, it looks like I am just a spectator.

I use quite a lot of mods, but most of them are character ones, here the biggest mods:
Inferno
StarStorm 2
Tinker's Satchel
VanillaVoid
SpikeStrip 2.0
Forgotten Relics
Mystic Items;
Here are some screenshots of it:
![Screenshot_1563](https://github.com/ikesicle/Providirector/assets/154853703/59376028-1a43-4a90-9476-dc1b0af3dbae)
![Screenshot_1562](https://github.com/ikesicle/Providirector/assets/154853703/fb42e4cf-0f78-48e9-9eb6-776d1a6bff1f)

**Comment by ikesicle** [comment]
The issue might be with Starstorm2. I never checked to see how the mod interacts with mods which add new, non-vanilla enemies to the game, but it's possible that Providirector just fails to process and add modded enemies for one reason or another. I'll look into it.

**Comment by ikesicle** [comment]
Update: It seems like because of how Starstorm2 handles entity names with the addition of the Empyrean elite type, Providirector halts while trying to populate the spawnable characters list. I'll try to get it fixed ASAP.

**Comment by 4ertos** [comment]
I've just checked about Startstorm2, I disabled Empyrean elites to spawn, fully disabled it in game, and then even deleted it, and still I have the same issue, I am not sure about Starstorm doing something.

**Comment by ikesicle** [comment]
Hm, OK. The error trace I got seemed to mention Starstorm on its own as well, though there might be a more general issue. Could you send me your entire modlist, so I can run tests on it?

**Comment by 4ertos** [comment]
Yeah, here's the import modpack code: 018cad15-d3f5-887d-58c3-18ffd3b6bcd1
