### ISSUE TITLE
Camera Bug.

### ISSUE THREAD

**Issue by 4ertos** [RileSamurott/Providirector#11]
All works except for camera targetting, that's something new.
Can't switch to any player after the 1.0.2 version, you have only focus on "auto" and it stays on some fictioned place.
Like this screenshot:
![Screenshot_1585](https://github.com/ikesicle/Providirector/assets/154853703/c40b3bb8-d61f-4901-93c6-24bc41b3be36)

**Comment by 4ertos** [comment]
![Screenshot_1586](https://github.com/ikesicle/Providirector/assets/154853703/24abba37-0006-4019-813f-ec5907c8b7b5)
Yeah, some maps are even worse. . .

**Comment by ikesicle** [comment]
I'll look into it. It seems like it's just not locking on to anything at all, which is very strange. I did change the lock-on code as part of re-enabling targeting for drones and Void enemies, so the problem probably lies there.

**Comment by 4ertos** [comment]
Thanks a lot for your quick support anyway, I didn't even think that you would acutally reply that fast and fix the issue like that, great effort.

**Comment by ikesicle** [comment]
New camera bug _should_ be fixed in 1.0.3, closing for now, but may be quickly re-opened
