### ISSUE TITLE
I can't shoot without swapping what I'm spectating (but im still alive)

### ISSUE THREAD

**Issue by TonTonTheBard** [RileSamurott/Providirector#3]
So, my friend and I played this mod, had a ton of fun, but the main issue I keep running into is that I spawn in spectating, then my character spawns in. Clicking m1 and m2 causes me to switch between spectating and playing; making it near impossible for me to play. I currently have starstorm 2, and a few character mods on. It became impossible without being able to fire at all.
I have no idea how to fix this or how to change the config for spectating.

**Comment by ikesicle** [comment]
Hi, thanks for leaving an issue! I think the issue might have something to do with how the mod tries to prevent the player from spawning in. Normally it just tries to intercept and stop the function call which actually spawns players in, but that might break if other mods are turned on - I never actually tested the mod while things like character mods were turned on.

In any case, I'm finally done with school, so I'll try and resolve some possible incompatibilities with some popular mods and character mods.

**Comment by TonTonTheBard** [comment]
Fantastic! Thank you so much. My friends and I love this mod and it has so much potential!

I wish you luck on the fixes!

**Comment by TonTonTheBard** [comment]
Another minor issue, I cannot spawn mithrix. He wont come out of his bubble.

**Comment by ikesicle** [comment]
Could you post the logs for the most recent run, if you still have them? There are usually triggers for mithrix which get caught by the logger, so I suspect they might have some useful info.

**Comment by TonTonTheBard** [comment]
i unfortunately do not have the logs for the run

**Comment by ikesicle** [comment]
That's alright - I have had issues in the past with mithrix not triggering too - I feel like it has something to do with the fact that the "Director" still counts as a character who is required to start the mithrix fight. I accidentally uploaded the wrong files in 0.1.2, so this should be fixed in 0.2.0!

**Comment by ikesicle** [comment]
Mithrix now spawns consistently on the latest update (0.2.1), closing this issue for now
