### ISSUE TITLE
Final boss camera bug

### ISSUE THREAD

**Issue by MagentaLizard** [RileSamurott/Providirector#4]
When there's 2 of the final bosses and the one my camera is focused on dies i get sent back to spectator mode and have to control the clone through it. Makes it impossible to kill anything or aim at all.

Mod list code 01894b4b-7dc8-1c32-be11-2b7a3150ef5a

Maybe making the clone of mithrix and voidling be controlled by ai would fix the issue? Or your camera can swap to the clone if the main one dies.

**Comment by ikesicle** [comment]
That's a pretty critical issue- thanks for pointing it out. I never tested the mod with Swarms active; should have been more careful.

As for the issue itself, yes, I think I could have one of them be initially player-controlled and the other be AI-controlled, then disable the AI and swap over to player control on the other one if the main one dies. It shouldn't be too difficult to implement, so hopefully I can get a patch out this week.

**Comment by ikesicle** [comment]
Solved in 0.3.0 update, which is now deployed. When swarms is active, one Mithrix will be AI-controlled and the other player-controlled. When killed, the player-controlled Mithrix will have its control diverted to the AI-controlled Mithrix instead.
