### ISSUE TITLE
Artifact of Honor

### ISSUE THREAD

**Issue by MagentaLizard** [RileSamurott/Providirector#5]
My normal enemies aren't elite by default when the artifact of honor is enabled.

**Comment by MagentaLizard** [comment]
Not entirely sure if it's a bug or meant to be like that

**Comment by ikesicle** [comment]
Not so much a bug; I just forgot to make the mod line up with artifacts lol - this is also why spawns aren’t doubled for Swarms, why spawned enemies don’t get Evolution items, why you can still spawn other enemies when Kin is active, etc.

I’m currently in China without access to a computer, so I can’t exactly fix this issue right now… I’ll hopefully get an update out before August ends. In the meantime, thanks for pointing this out- I normally don’t play with Artifacts so this never crossed my mind lol

**Comment by ikesicle** [comment]
Solved in 0.3.0 update, which is now deployed. Honour now makes the director spawn enemies at a reduced-cost Tier1 by default, and the Tier1 Key does nothing.
