### ISSUE TITLE
Weird map bug with new update

### ISSUE THREAD

**Issue by MagentaLizard** [RileSamurott/Providirector#7]
Other's seem to see the map differently and can walk on things that i cannot see or spawn enemies on. Also the final boss jump pads were not visible for them.

**Enabled Mods**

018a2a72-8ecc-8cc9-8f29-e50e0b7fd206

**Comment by ikesicle** [comment]
That's weird indeed. The mod mostly intercepts game logic code, so I can't fathom for the life of me how it could be affecting how the stage renders. 

I can't test it at the moment, but can you go into a bit more detail? For example, when you say "cannot spawn enemies", are you actually unable to spawn any enemies, or do spawned enemies fall through the map somehow? As for the visual glitches, does it just look like the survivors are walking on air or through walls?

**Comment by MagentaLizard** [comment]
> That's weird indeed. The mod mostly intercepts game logic code, so I can't fathom for the life of me how it could be affecting how the stage renders.
> 
> I can't test it at the moment, but can you go into a bit more detail? For example, when you say "cannot spawn enemies", are you actually unable to spawn any enemies, or do spawned enemies fall through the map somehow? As for the visual glitches, does it just look like the survivors are walking on air or through walls?

Survivors are walking on air in some spots and monsters i spawn there fall as if there really is nothing there. It's like they're playing on a different stage variation than the one i see.

**Comment by ikesicle** [comment]
@MagentaLizard After testing (2 players, with the mod config you sent), I can't seem to replicate the map glitch - everything seems to work fine. If you're still experiencing the bug, could you send the log files immediately after a bugged run? It might help to pinpoint what's causing the issue.

**Comment by ikesicle** [comment]
Closing this for now to see if it's fixed in the latest update
