### ISSUE TITLE
Monsters fall to the ground and die

### ISSUE THREAD

**Issue by Muchaszewski** [RileSamurott/Providirector#8]
**Describe the bug briefly**

Monsters fall to the ground and die :(

**Screenshots**
Easy to imagine I guess

**Suggestions**
Shoot a ray cast towards the ground for all non-flying units and spawn them there instead of flying

**Comment by ikesicle** [comment]
Oh 🌚 I didn't think anyone would bring this up
I'll try to add a fix for it in the next update. Although, for me there's something comedic about spawning enemies in midair like that, so it'll be toggleable.

**Comment by Muchaszewski** [comment]
That's true 😆 Maybe you can give them fall damage resistance so that they will survive the landing! (In addition to the option with raycast)

**Comment by ikesicle** [comment]
Fixed in the latest update! There is now a toggleable option server-side to snap spawns to the closest ground node, effectively preventing this issue.
